### ISSUE TITLE
7.1.2  Productr type name

### ISSUE THREAD

**Issue by GmanG** [colinmurphy/magento-exam-notes#17]
Hi,

is it correct product type name like 'platnum'? Maybe platinum?

In article 7.1.2 https://github.com/colinmurphy/magento-exam-notes/blob/master/7.%20Catalog/%201.%20Product%20Types/2.%20Create%20Product%20Type.md

Thx.

**Comment by colinmurphy** [comment]
Apologies about the delay.

Thanks for spotting that grammatical error. I have pushed a small commit to fix this - https://github.com/colinmurphy/magento-exam-notes/commit/dd44984a392feaf2e8fb5a4a3e904996c4694cd5
