### ISSUE TITLE
Troubleshoot and customize Magento indexes error in class name

### ISSUE THREAD

**Issue by choussamaster** [colinmurphy/magento-exam-notes#8]
In the last line
"Mage_CatalogIndex_Model_Indexer_Stock"
is false the correct class is
"Mage_CatalogInventory_Model_Indexer_Stock"

**Comment by colinmurphy** [comment]
Thanks choussamaster

I have updated the class name - https://github.com/colinmurphy/magento-exam-notes/blob/master/7.%20Catalog/5.%20Other%20Skills/4.%20Troubleshoot%20and%20customize%20Magento%20indexes.md
